export default  {
    CREATED: 'User is successfully created',
    StockNotFound:  "Stock was not found",
    StockPrediction: "Stock prediction Not Successful",
    DUPLICATE_EMAIL : 'Email duplicate is not allowed',
    FAILED_EMAIL: 'Verification code was not successfully sent',
    INCORRECT_OTP: 'Invalid code provided or code has expired',
    INCORRECT_DETAIL : 'Email or Password is incorrect || Account is not yet verified',
    EMAIL_NOT_VERIFIED: 'You are yet to verify your email',
    UNAUTHORIZED: 'User is not unauthorized',
    VERIFIED: 'Confirmation code has been sent to your email already or your account is already verified',
    INVAILD_USER_REQUEST: 'User is not found in our database',
    VERIFIED_USER: 'Account is being verified',
    RESEND_CODE: 'Check your email for verification code',
    USER_LOGGEDIN: 'User is loggedin',
    RESET_PASSWORD_OTP: 'We sent an otp to your email',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    CANNOT_UPLOAD_FILE: 'Sorry you are not unauthoruized to make this request',
    FILE_UPLOADED : 'You have changed your profile',
    UNABLE_TO_SEND_OTP :"We were unable to send otp.. Please provide  us with valid email",
    UNABLE_TO_CHANGE_THIS_PASSWORD: "Sorry we are unable to change your password",
    UNABLE_TO_VERIFY_EMAIL: 'Unable to verify this account'
}