# .github/workflows/build.yml
name: Node CI

on: [push]

jobs:
  build:

    run-on: ${( matrix.os )}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${( matrix.node-version )}
      uses: actions/setup-node@v1
      with:
        node-version: ${( matrix.node-version )}
    - name: npm install, build, and test
      run: |
        npm ci
        npm install && run build --if-present
        npm test
      env:
      CI: true
